name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      pull-requests: read
    uses: oxHive/pipelines/.github/workflows/rust-release.yml@main
    with:
      package-name: oxvessel
      binary-name: vessel
    secrets: inherit
